name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "Gnome Data Stats v__VERSION__"
          releaseBody: "Download the latest version below."
          releaseDraft: true
          prerelease: false
